name: Discord Commit Notifier

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Format Commit List
        id: format_commits
        uses: actions/github-script@v6
        with:
          script: |
            const commits = context.payload.commits;
            if (!commits) {
              return "No commit information found.";
            }
            
            const commit_messages = commits.map(commit => {
              const hash = commit.id.substring(0, 7);
              const message = commit.message.split('\n')[0]; // Use only the first line of the commit message
              return `• [\`${hash}\`](${commit.url}) ${message}`;
            });

            return commit_messages.join('\n');

      - name: Discord Webhook Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "Hammer & Heart | Github"
          title: "New Push to `${{ github.ref_name }}`"
          description: |
            **Commits:**
            ${{ steps.format_commits.outputs.result }}

            **Pushed by:** `${{ github.actor }}`
          url: "${{ github.event.compare }}"
          color: 39423 # A pleasant green color :D